name: apps.technical.sera_astra
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  shared_preferences: ^2.0.6
  dio: ^4.0.0
  cached_network_image: ^3.1.0
  image: ^3.0.2
  get_it: ^7.1.3
  dropdown_search: ^5.0.2
  showcaseview: ^2.0.3
  intl: ^0.17.0
  introduction_screen: ^3.0.2
  skeleton_text: ^3.0.0
  connectivity_plus: ^3.0.2
  google_fonts: ^5.1.0
  local_auth: ^2.0.0
  fluttertoast: ^8.2.1
  font_awesome_flutter: ^9.0.0
  flutter_launcher_icons: ^0.9.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo1.png"
 